function [errorcode, errorcode_description] = agt_awg_generatesoftwaremarker(varargin)
% Agilent N6030 Series Matlab Interface, Release 1.25
% Copyright © 2004,2005,2006 Agilent Technologies, Inc.
%
% This function generates a software marker event.  This feature is normally used
% when one of the front panel marker ports has been configured to output one of 
% the four software markers. One of four possible software markers is generated by
% this function. For example, assume the front panel marker 3 output has been 
% configured to output software marker 'sw2'. Calling this function to generate a
% software marker event for software marker 2 ('sw2') will then cause a marker output
% on the front panel marker 3 port. As can be seen in this example, some confusion may
% result when a front panel marker is connected to a software marker of a different
% number. When possible, associating numbered software marker events with the
% matching numbered front panel marker will reduce the possibility of confusion.
%
% function [ errorcode, errorcode_description] = agt_awg_generatesoftwaremarker(handle, marker)
%
% Output:        
%   errorcode               integer     less than 0 is an error (IVI error)
%   errorcode_description   string      error/warning message
% Input:
%   handle                  integer     a handle to the instrument (see agt_awg_open)
%   marker                  string      'sw1', 'sw2', 'sw3', or 'sw4', 
%                                       or integer values 1, 2, 3 or 4.
%
%   See Also: agt_awg_setstate.m and the 'mkrsource' attribute.
%

if (nargin < 1) 
    error('Invalid input parameters.');
end

if ( ~isnumeric(varargin{1}) )
   error('Instrument Handle must be a number');
end

if ( isnumeric(varargin{2} ) )
    if varargin{2} == 1 || varargin{2} == 2 || varargin{2} == 3 || varargin(2) == 4
        varargin{2} = ['sw' num2str(varargin{2})];
    else
      errorcode = int32(-1074135025);
      errorcode_description = 'Invalid input parameters. See help for details.';
      return;
    end
end

[errorcode, errorcode_description] = N6030MEX('generatesoftwaremarker',varargin{1},varargin{2});
